### ISSUE TITLE
Configuration.yaml

### ISSUE THREAD

**Issue by oshimo** [abaker/emu2influx#1]
Could you share your sensor setup in the configuration.yaml?

**Comment by abaker** [comment]
Sorry, I've been meaning to set this up myself but haven't gotten around to it yet. I could probably try to write one, what did you want to put in your sensor?

**Comment by oshimo** [comment]
Current usage would be awesome

**Comment by abaker** [comment]
I'm going off the [full configuration](https://www.home-assistant.io/components/sensor.influxdb/#full-configuration) section of their docs, haven't tested this myself

Here is the query I'm trying to reproduce (`where time < now()` is in there because the sensor config requires a `where` clause)

```
$ influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 1.0.2
InfluxDB shell version: 1.0.2
> use rainforest
Using database rainforest
> select last(demand) as demand from demand where time < now()
name: demand
------------
time                    demand
1541102210000000000     0.927
```

Let me know if this works

```
sensor:
  platform: influxdb
  host: localhost
  username: home-assistant
  password: password
  queries:
    - name: current demand
      value_template: '{{ demand }}'
      group_function: last
      where: 'time < now()'
      measurement: '"demand"'
      field: demand
      database: rainforest
```

**Comment by oshimo** [comment]
Unfortunately it is coming up blank on HA. I was able to pull my time and demand in influx though.

**Comment by abaker** [comment]
Can you try `value_template: '{{ demand | float }}'`

**Comment by oshimo** [comment]
It works if i set it to: value_template: '{{ value | round(1) }}'

Thanks for your help and this whole setup!

**Comment by abaker** [comment]
Cool! Would you mind submitting a PR or sending me your config and I'll add it to the repo?
